WIP: hotfix for docker client when docker daemon is not running
tethysplatform/tethys pull request #594
Opened 2020-09-10 22:52 UTC by sdc50

fixes #589

2020-09-10 22:52 UTC, sdc50 commented
Still need to update tests

2020-09-11 19:56 UTC, swainn commented
@sdc50 let's enable the osx testing again to verify that the fix is working as we discussed in scrum.

2020-09-14 16:02 UTC, swainn requested changes

2020-09-14 16:02 UTC, swainn commented on setup.cfg
> +version = 3.1.1
This needs to be 3.2.0 for master.

2020-09-15 16:21 UTC, sdc50 commented
replaced by #597

2020-09-15 16:21 UTC, closed without merging