Steem71 cesium time enable
tethysplatform/tethys pull request #677
Opened 2021-03-26 19:24 UTC by htran84

2021-03-26 20:21 UTC, swainn requested changes

2021-03-26 20:21 UTC, swainn commented on tethys_gizmos/gizmo_options/map_view.py
> +        times (list): only for Cesium. List of start time for geoserver image mosaic layers. (e.g.: ["20210322T112511Z", "20210322T122511Z", "20210322T132511Z"])
Change to: 

```
times (list): List of time steps if layer is time-enabled. Times should be represented as strings in ISO 8601 format (e.g.: ["20210322T112511Z", "20210322T122511Z", "20210322T132511Z"]). Currently only supported in CesiumMapView.
```

2021-03-26 20:21 UTC, swainn commented on tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
> +    cesium_time_callback = function (interval) {
Remove space between `function` and call arguments: `cesium_time_callback = function(interval) {`

2021-03-26 20:21 UTC, swainn commented on tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
> +                        // times should be in this format "["20210322T112511Z", "20210322T122511Z", "20210323T032511Z"]"
`// times should a JSON array string with times in ISO 8601 format: "["20210322T112511Z", "20210322T122511Z", "20210323T032511Z"]"`

2021-03-26 20:21 UTC, swainn commented on tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
> +                            iso8601Dates: JSON.parse(curr_layer.times),
why not use the `times` variable here (see line 200)?

2021-03-26 20:21 UTC, swainn commented on tethys_gizmos/static/tethys_gizmos/js/cesium_map_view.js
> +                        clock.multiplier = 600;
Why 600?

2021-03-29 16:24 UTC, swainn approved these changes

2021-03-29 16:31 UTC, sdc50 approved these changes

2021-03-29 16:32 UTC, merged